"""``caesar init`` — generate a working configuration on a fresh box (ADR-0029).

Writes a self-contained config in the target directory: ``.env`` with
fresh secrets, a minimal ``policy.yaml``, a Praetor NKEY seed, and
the ``./var/`` directory the SQLite engine expects. The operator
edits one line in ``.env`` (the LLM API key, if they pick a
cloud provider) and ``caesar praetor serve`` works.

The command is intentionally idempotent. Re-running it on a populated
directory refuses to overwrite anything unless the operator passes
``--force``. Even with ``--force`` we never overwrite ``./var/`` —
that's where the operator's data lives.
"""

from __future__ import annotations

import contextlib
import secrets
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from caesar.legion.bootstrap import generate_worker_identity

ENV_FILENAME = ".env"
POLICY_FILENAME = "policy.yaml"
NKEY_FILENAME = "praetor.nkey"
VAR_DIRNAME = "var"


def _generate_token() -> str:
    """Random URL-safe token suitable for the dashboard / signing key."""

    return secrets.token_urlsafe(48)


def _env_contents(*, dashboard_token: str, signing_key: str) -> str:
    return dedent(
        f"""\
        # Generated by `caesar init` (ADR-0029).
        # Edit values then run `caesar praetor migrate && caesar praetor serve`.

        # --- LLM provider -------------------------------------------------
        # Pick one provider and fill in the matching API key (or use
        # ollama for a fully-local install).
        CAESAR_LLM__PROVIDER=anthropic
        CAESAR_LLM__MODEL=claude-haiku-4-5-20251001
        CAESAR_LLM__ANTHROPIC__API_KEY=

        # OpenAI alternative:
        # CAESAR_LLM__PROVIDER=openai
        # CAESAR_LLM__MODEL=gpt-4o-mini
        # CAESAR_LLM__OPENAI__API_KEY=sk-...

        # Ollama alternative (fully local — needs `ollama serve` running):
        # CAESAR_LLM__PROVIDER=ollama
        # CAESAR_LLM__MODEL=llama3.1:8b-instruct
        # CAESAR_LLM__OLLAMA__BASE_URL=http://localhost:11434

        # --- Home Assistant bridge (optional) -----------------------------
        # CAESAR_HA__URL=http://homeassistant.local:8123
        # CAESAR_HA__TOKEN=

        # --- Policy engine -----------------------------------------------
        CAESAR_POLICY__RULES_PATH=./{POLICY_FILENAME}

        # --- Dashboard ---------------------------------------------------
        # The token is what you type at /dashboard/login. The signing
        # key is held separately so rotating the token alone doesn't
        # invalidate sessions (SR-006).
        CAESAR_DASHBOARD__TOKEN={dashboard_token}
        CAESAR_DASHBOARD__SIGNING_KEY={signing_key}

        # --- Bus (NATS) --------------------------------------------------
        # Disabled by default; enable when you want Legion workers.
        # CAESAR_BUS__ENABLED=true
        # CAESAR_BUS__URL=nats://127.0.0.1:4222
        # For multi-host workers (ADR-0027), point at the seed below:
        # CAESAR_BUS__AUTH__ENABLED=true
        # CAESAR_BUS__AUTH__NKEY_SEED_PATH=./{NKEY_FILENAME}
        """
    )


def _policy_contents() -> str:
    return dedent(
        """\
        # Generated by `caesar init` (ADR-0029).
        # Operator decides what CAESAR is allowed to do. The deny-all
        # default that ships when no policy is configured remains the
        # safe fallback; this file lets you opt into specific actions.

        version: 1

        # Home Assistant services CAESAR may invoke. Uncomment the
        # services that match what you actually want it to control.
        # Use the constrained form with target.entity_id (SR-005) to
        # restrict by entity:
        #
        #   - service: light.turn_on
        #     target:
        #       entity_id: [light.kitchen]
        allowed_services: []
        #   - light.toggle
        #   - light.turn_on
        #   - light.turn_off
        #   - switch.turn_on
        #   - switch.turn_off

        # Legion tool workers CAESAR may dispatch. calculator is safe
        # by default (no network, no creds); add web_search and
        # calendar_read only once you've configured their workers.
        allowed_tools:
          - calculator
        #   - web_search
        #   - calendar_read
        """
    )


@dataclass(frozen=True)
class InitPlan:
    """Files and directories ``caesar init`` will touch.

    Returned by :func:`compute_plan` so the CLI command can report what
    it intends to do before doing it; also useful for tests.
    """

    env_path: Path
    policy_path: Path
    nkey_path: Path
    var_dir: Path

    @property
    def files(self) -> list[Path]:
        return [self.env_path, self.policy_path, self.nkey_path]


def compute_plan(target_dir: Path) -> InitPlan:
    """Resolve the paths ``caesar init`` will write under ``target_dir``."""

    return InitPlan(
        env_path=target_dir / ENV_FILENAME,
        policy_path=target_dir / POLICY_FILENAME,
        nkey_path=target_dir / NKEY_FILENAME,
        var_dir=target_dir / VAR_DIRNAME,
    )


def existing_artifacts(plan: InitPlan) -> list[Path]:
    """Return the subset of ``plan.files`` that already exist on disk."""

    return [p for p in plan.files if p.exists()]


def init_workspace(target_dir: Path, *, force: bool = False) -> InitPlan:
    """Generate a fresh CAESAR config in ``target_dir``.

    Returns the resolved :class:`InitPlan` so the caller can print a
    summary. Raises :class:`FileExistsError` (carrying the conflict list)
    when any config file already exists and ``force`` is False.
    """

    target_dir.mkdir(parents=True, exist_ok=True)
    plan = compute_plan(target_dir)
    if not force:
        clashes = existing_artifacts(plan)
        if clashes:
            joined = ", ".join(str(p) for p in clashes)
            raise FileExistsError(
                f"refusing to overwrite existing files: {joined}. Pass --force to replace.",
            )

    dashboard_token = _generate_token()
    signing_key = _generate_token()
    identity = generate_worker_identity(name="praetor")

    plan.env_path.write_text(
        _env_contents(dashboard_token=dashboard_token, signing_key=signing_key),
        encoding="utf-8",
    )
    plan.policy_path.write_text(_policy_contents(), encoding="utf-8")
    plan.nkey_path.write_text(identity.seed + "\n", encoding="utf-8")
    plan.var_dir.mkdir(parents=True, exist_ok=True)
    # Best-effort: tighten permissions on the NKEY. POSIX only; ignored
    # on Windows where the equivalent is folder ACLs the operator
    # already controls.
    # pragma: no cover - chmod is POSIX-only; Windows raises NotImplementedError
    with contextlib.suppress(OSError, NotImplementedError):
        plan.nkey_path.chmod(0o600)
    return plan


def format_summary(plan: InitPlan) -> str:
    """Human-readable summary for stdout after a successful init."""

    return dedent(
        f"""\
        === Initialised CAESAR config ===

        Wrote:
          {plan.env_path}
          {plan.policy_path}
          {plan.nkey_path}     (mode 0600; do NOT commit)
          {plan.var_dir}/      (state lives here)

        Next steps:
          1. Edit {plan.env_path.name} and set your LLM API key.
          2. Apply schema:   caesar praetor migrate
          3. Run the brain:  caesar praetor serve
          4. Open the dashboard at http://127.0.0.1:8000/dashboard

        For Home Assistant, uncomment CAESAR_HA__URL / TOKEN in
        {plan.env_path.name} and add allowed services to {plan.policy_path.name}.
        """
    )
